// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rooadwjinmjwwrtuypzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvb2Fkd2ppbm1qd3dydHV5cHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzI1NDIsImV4cCI6MjA2NjU0ODU0Mn0.N2WWPCbwOjkhuE769aME4qKPtfv_-tubTm8voMM124Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);